[package]
name = "op-export"
version = "0.1.0"
authors = ["Peter Schuller <peter.schuller@infidyne.com>"]
edition = "2018"

[dependencies]
clap = "2"
crossbeam = "0"
anyhow = "1"
serde_json = "1"
tempfile = "3"
rand = "0"